server:
  port: 80
  servlet:
    path: /
eureka:
  client:
    service-url:
      defaultZnoe: http://localhost:8761/eureka/
spring:
  application:
    name: zuul-server
zuul:
  routes:
    api-test:
      path: /api/test/**
      service-id: test-system
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
    max-total-connections: 20
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000